[FileDialog]
history=file:///home/statick/Imágenes/obs, file:///home/statick/Pictures/wallpapers, file:///home/statick/Imágenes, file:///home/statick/Pictures/Screenshots, file:///home/statick/Descargas, file:///home/statick/Documentos/gnu-linux
lastVisited=file:///home/statick/Documentos/gnu-linux
qtVersion=6.8.0
shortcuts=file:, file:///home/statick
sidebarWidth=78
treeViewHeader=@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\x3\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x2\x1f\0\0\0\x4\x1\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x64\xff\xff\xff\xff\0\0\0\x81\0\0\0\0\0\0\0\x4\0\0\x1\x1e\0\0\0\x1\0\0\0\0\0\0\0\x43\0\0\0\x1\0\0\0\0\0\0\0G\0\0\0\x1\0\0\0\0\0\0\0w\0\0\0\x1\0\0\0\0\0\0\x3\xe8\0\xff\xff\xff\xff\0\0\0\0)
viewMode=Detail
