[General]
filedialog-path=@Variant(\0\0\0\x11\0\0\0nfile:///home/statick/V%C3%ADdeos/django/Curso%20Django.%20Proyecto%20web%20completo%20V.%20V%C3%ADdeo%2030.mp4)
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\x2\xb3\0\0\0+\0\0\x5K\0\0\x2\xf5\0\0\x2\xb3\0\0\0+\0\0\x5K\0\0\x2\xf5\0\0\0\0\0\0\0\0\x5V\0\0\x2\xb3\0\0\0+\0\0\x5K\0\0\x2\xf5)

[FullScreen]
pos=@Point(283 704)
screen=@Rect(0 0 1366 768)
wide=false

[MainWindow]
adv-controls=0
bgSize=@Size(100 30)
pl-dock-status=true
playlist-visible=true
playlistSize=@Size(665 641)
status-bar-visible=false

[OpenDialog]
advanced=false
size=@Size(526 423)

[Playlist]
headerStateV2=@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\0\xff\xff\xff\xff\x1\0\0\0\0\0\0\0\0\0\0\0\r\xec\xf\0\0\0\t\0\0\0\x3\0\0\0\x64\0\0\0\x2\0\0\0\x64\0\0\0\a\0\0\0\x64\0\0\0\x6\0\0\0\x64\0\0\0\x5\0\0\0\x64\0\0\0\v\0\0\0\x64\0\0\0\n\0\0\0\x64\0\0\0\t\0\0\0\x64\0\0\0\b\0\0\0\x64\0\0\x4\x88\0\0\0\r\x1\x1\0\x1\0\0\0\0\0\0\0\0\0\0\0\0\x64\xff\xff\xff\xff\0\0\0\x81\0\0\0\0\0\0\0\r\0\0\x1\xd0\0\0\0\x1\0\0\0\0\0\0\0P\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\x64\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\x2\x4\0\0\0\x1\0\0\0\0\0\0\x3\xe8\0\0\0\0\x64)
leftSplitterGeometry=@ByteArray(\0\0\0\xff\0\0\0\x1\0\0\0\x2\0\0\0\xc0\0\0\0\x80\x1\xff\xff\xff\xff\x1\0\0\0\x2\0)
splitterSizes=@ByteArray(\0\0\0\xff\0\0\0\x1\0\0\0\x2\0\0\0\xb4\0\0\x1\xa4\x1\xff\xff\xff\xff\x1\0\0\0\x1\0)
view-mode=1
zoom=0

[RecentsMRL]
list=file:///home/statick/2024-12-04%2010-15-45.mp4, file:///home/statick/2024-12-04%2010-14-20.mp4, file:///home/statick/V%C3%ADdeos/django/Curso%20Django.%20Proyecto%20web%20completo%20V.%20V%C3%ADdeo%2030.mp4, file:///home/statick/V%C3%ADdeos/django/Curso%20Django.%20Plantillas%20I.%20V%C3%ADdeo%205.mp4, file:///home/statick/V%C3%ADdeos/django/Curso%20Django.%20Par%C3%A1metros%20en%20URL.%20V%C3%ADdeo%204.mp4, file:///home/statick/V%C3%ADdeos/django/Curso%20Django.%20Creaci%C3%B3n%20de%20primera%20p%C3%A1gina.%20V%C3%ADdeo%203.mp4, file:///home/statick/V%C3%ADdeos/django/Curso%20Django.%20Creaci%C3%B3n%20primer%20proyecto.%20V%C3%ADdeo%202.mp4, file:///home/statick/V%C3%ADdeos/django/Curso%20Django%EF%BC%9A%20Proyecto%20completo%20XXX.%20Mensajes%20de%20error.%20V%C3%ADdeo%2065.mp4, file:///home/statick/V%C3%ADdeos/django/Curso%20Django.%20Introducci%C3%B3n%20e%20Instalaci%C3%B3n.V%C3%ADdeo%201.mp4, file:///home/statick/V%C3%ADdeos/django/Curso%20Django.%20API%20Forms%20V%C3%ADdeo%2025.mp4, directory:///home/statick/V%C3%ADdeos/django, file:///home/statick/V%C3%ADdeos/Aprendiendo%20Django%20%2319%EF%BC%9A%20Creando%20una%20tienda%20virtual%20con%20django.mp4, file:///home/statick/V%C3%ADdeos/TALLER%20EN%20VIVO%EF%BC%9A%20C%C3%B3mo%20hacer%20documentos%20y%20presentaciones%20con%20Markdown.mp4
times=0, 0, 223650, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0

[playlistdialog]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\x1\x7f\0\0\0\"\0\0\x3\xd6\0\0\x2\xdd\0\0\x1\x7f\0\0\0\"\0\0\x3\xd6\0\0\x2\xdd\0\0\0\0\0\0\0\0\x5V\0\0\x1\x7f\0\0\0\"\0\0\x3\xd6\0\0\x2\xdd)
